### ISSUE TITLE
Feature request: Allow missing .eslint-rebase.json file

### ISSUE THREAD

**Issue by binary64** [AndersDJohnson/eslint-plugin-rebase#26]
It would be great to have a missing .eslint-rebase.json file as just an empty array, instead of aborting with a failure.

**Comment by AndersDJohnson** [comment]
@binary64 Are you seeing hard errors without one? I think it just logs a warning and doesn't suppress any rules as if you weren't using the tool.

<img width="896" alt="Screen Shot 2021-06-15 at 6 26 53 PM" src="https://user-images.githubusercontent.com/615381/122136020-4bfe9300-ce07-11eb-9ac7-52baccc4cfea.png">

**Comment by binary64** [comment]
Hrm my bad, maybe I got confused with the red coloring. I would vote for yellow, if it's just a warning. Also if you say something like "To create one, type xxx" would be awesome for the DX.

**Comment by binary64** [comment]
Seems to work good -- thank you!
