### ISSUE TITLE
Support --fix

### ISSUE THREAD

**Issue by binary64** [AndersDJohnson/eslint-plugin-rebase#28]
Right now, --fix doesn't work when this plugin is in use.

Suggested fix:

Add this to processor.ts:
```
supportsAutofix: true
```

**Comment by AndersDJohnson** [comment]
@binary64 Can you explain more? I don't get any errors running `eslint --fix` with the plugin enabled - whether it's configured to ignore any errors or not.

**Comment by binary64** [comment]
Are you on latest estlint ? `"eslint": "~7.28.0"`

**Comment by AndersDJohnson** [comment]
@binary64 I don't think I've attempted to implement auto-fixing for this plugin. Are you saying that this plugin is breaking auto-fix for other rules and plugins? Or is this a feature request to support auto-fixing as a way of reading like we can with our `eslint-rebase` CLI?

**Comment by binary64** [comment]
Yes, without this I'm unable to autofix using other rules/plugins.

I don't think an autofixer for your plugin is suitable, I prefer your method of calling the cli bin directly.

**Comment by AndersDJohnson** [comment]
@binary64 Gotcha, I reproduced the same issue! Should be fixed in #41. I just did a publish of `v0.1.0` that should have all of the other changes you requested as well. Let me know if they work for you, thanks for using! 🚀

**Comment by binary64** [comment]
Seems to work good -- thank you!
