### ISSUE TITLE
Possible pointless entries in .eslint-rebase.json

### ISSUE THREAD

**Issue by binary64** [AndersDJohnson/eslint-plugin-rebase#44]
Hi again :)

Loving your plugin, and am using it.

I have these lines in my `.eslint-rebase.json` file
```
  "apps/web/types/blah.d.ts": {}
```

Do you think these are needed? If not, could the plugin not output these lines, in order to keep the file a bit cleaner?

**Comment by AndersDJohnson** [comment]
@binary64 Fixed in #48 and published with v0.1.1.
